# Generated by Django 5.2.7 on 2025-11-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado até'),
        ),
    ]
