# Generated by Django 5.2.7 on 2025-10-30 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(limit_choices_to={'role': 'INSTRUCTOR'}, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='Instrutores'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='courses_enrolled', to=settings.AUTH_USER_MODEL, verbose_name='Alunos'),
        ),
    ]
