# Generated by Django 5.2.7 on 2025-10-30 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título da aula')),
                ('content', models.TextField(blank=True, verbose_name='Conteúdo')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duração estimada')),
                ('video_url', models.URLField(blank=True, verbose_name='Link do vídeo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('course', 'order'), name='unique_lesson_order_per_course')],
            },
        ),
    ]
